dedup short cmdline args
because

thread 'main' panicked at /Users/donaldturnworth/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.40/src/builder/debug_asserts.rs:112:17:
Command compare: Short option names must be unique for each argument, but '-g' is in use by both 'gnuplot' and 'significant_only'